# Generated by Django 6.0.3 on 2026-03-27 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_add_public_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='key_salt',
            field=models.BinaryField(blank=True, default=b'', help_text='Salt used for PBKDF2 key derivation.', verbose_name='PBKDF2 salt'),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
